export const dbTop = [
  {
    id: "BRA",
    nombre: "Brazil",
    bandera: "https://flagcdn.com/w320/br.png",
    continente: "Americas",
    capital: "Brasília",
    subregion: "South America",
    poblacion: 212559409,
  },
  {
    id: "VEN",
    nombre: "Venezuela",
    bandera: "https://flagcdn.com/w320/ve.png",
    continente: "Americas",
    capital: "Caracas",
    subregion: "South America",
    poblacion: 28435943,
  },
  {
    id: "ARG",
    nombre: "Argentina",
    capital: "Buenos Aires",
    bandera: "https://flagcdn.com/w320/ar.png",
    continente: "Americas",
    subregion: "South America",
    poblacion: 45376763,
  },
  {
    id: "COL",
    nombre: "Colombia",
    capital: "Bogotá",
    bandera: "https://flagcdn.com/w320/co.png",
    continente: "Americas",
    subregion: "South America",
    poblacion: 50882884,
  },
  {
    bandera: "https://flagcdn.com/w320/mx.png",
    capital: "Mexico City",
    continente: "Americas",
    id: "MEX",
    nombre: "Mexico",
    subregion: "North America",
    poblacion: 128932753,
  },
  {
    id: "DEU",
    nombre: "Germany",
    capital: "Berlin",
    bandera: "https://flagcdn.com/w320/de.png",
    continente: "Europe",
    subregion: "Western Europe",
    poblacion: 83240525,
  },
  {
    id: "JPN",
    nombre: "Japan",
    bandera: "https://flagcdn.com/w320/jp.png",
    continente: "Asia",
    capital: "Tokyo",
    subregion: "Eastern Asia",
    poblacion: 125836021,
  },
];
